# Generated by Django 5.0 on 2023-12-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjid',
            name='location',
            field=models.CharField(blank=True, help_text='Masjid manzili', max_length=255, null=True, verbose_name='Manzil'),
        ),
    ]
