# Generated by Django 5.0 on 2023-12-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0002_masjid_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjid',
            name='qisqa_tavsif',
            field=models.TextField(blank=True, help_text='Masjid haqida qisqa tavsif', null=True, verbose_name='Qisqa tavsif'),
        ),
    ]
