# Generated by Django 5.0 on 2023-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0003_masjid_qisqa_tavsif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name_cyrl',
            field=models.CharField(blank=True, help_text='Tumanning kirillcha nomi', max_length=255, null=True, verbose_name='Kirill'),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='name_cyrl',
            field=models.CharField(blank=True, help_text='Masjidning kirillcha nomi', max_length=255, null=True, verbose_name='Kirill'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_cyrl',
            field=models.CharField(blank=True, help_text='Viloyat/Shaxarning kirillcha nomi', max_length=255, null=True, verbose_name='Kirill'),
        ),
    ]
