# Generated by Django 5.0 on 2023-12-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0004_alter_district_name_cyrl_alter_masjid_name_cyrl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mintaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(help_text='Mintaqaning lotincha nomi', max_length=255, verbose_name='Lotin')),
                ('name_cyrl', models.CharField(blank=True, help_text='Mintaqaning kirillcha nomi', max_length=255, null=True, verbose_name='Kirill')),
                ('name_ru', models.CharField(blank=True, help_text='Mintaqaning ruscha nomi', max_length=255, null=True, verbose_name='Rus')),
                ('mintaqa_id', models.CharField(help_text='Mintaqaning IDsi', max_length=255, verbose_name='Mintaqa IDsi')),
                ('viloyat', models.CharField(choices=[('1', 'Toshkent'), ('2', 'Andijon'), ('99', 'Boshqa')], help_text='Mintaqa joylashgan viloyat', max_length=255, verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Mintaqa',
                'verbose_name_plural': 'Mintaqalar',
            },
        ),
        migrations.AlterField(
            model_name='masjid',
            name='hufton',
            field=models.CharField(help_text="Masjidda xufton namozi o'qilish vaqti", max_length=255, verbose_name='Xufton'),
        ),
        migrations.CreateModel(
            name='NamozVaqti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milodiy_oy', models.IntegerField(help_text='Milodiy oy', max_length=255, verbose_name='Milodiy oy')),
                ('xijriy_oy', models.IntegerField(help_text='Xijriy oy', max_length=255, verbose_name='Xijriy oy')),
                ('milodiy_kun', models.IntegerField(help_text='Milodiy kun', max_length=255, verbose_name='Milodiy kun')),
                ('xijriy_kun', models.IntegerField(help_text='Xijriy kun', max_length=255, verbose_name='Xijriy kun')),
                ('vaqtlari', models.CharField(help_text='Tong | Quyosh | Peshin | Asr | Shom | Xufton', max_length=255, verbose_name='Vaqtlari')),
                ('mintaqa', models.ForeignKey(help_text='Mintaqa', on_delete=django.db.models.deletion.CASCADE, to='jamoatnamozlariapp.mintaqa', verbose_name='Mintaqa')),
            ],
        ),
    ]
