# Generated by Django 5.0 on 2023-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamoatnamozlariapp', '0005_mintaqa_alter_masjid_hufton_namozvaqti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namozvaqti',
            name='mintaqa',
        ),
        migrations.AlterField(
            model_name='masjid',
            name='hufton',
            field=models.CharField(help_text="Masjidda hufton namozi o'qilish vaqti", max_length=255, verbose_name='Hufton'),
        ),
        migrations.DeleteModel(
            name='Mintaqa',
        ),
        migrations.DeleteModel(
            name='NamozVaqti',
        ),
    ]
